[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"
  command = "npm run dev"
  targetPort = 5173   # Vite default (not 8080, unless you changed it)
  port = 8888

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["razorpay"]
